// @generated by Hollywood. Do not edit by hand.

import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { teardownMachine } from "../../../../../ci/teardown-machine.ts";

void runGitHubAction(teardownMachine);
